# Generated by Django 3.0.2 on 2020-01-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('bid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=30, unique=True)),
                ('loadFlag', models.BooleanField(default=False)),
                ('bstate', models.CharField(default='{}', max_length=1000)),
            ],
        ),
    ]
